Locale: en
CompatibilityMode: true
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: 280
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
ProtectPilotedCrafts: true
DisableSpillProtection: false
RequireCreatePerm: false
TNTContactExplosives: true
DisableCrates: false
FadeWrecksAfter: 0
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
BlockQueueChunkSize: 1000
AllowCrewSigns: true
SetHomeToCrewSign: false
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
TownyBlockMoveOnSwitchPerm: false
TownyBlockSinkOnNoPVP: false
TownyWorldHeightLimits:
  world:
    worldMin: -1
    worldMax: -1
    aboveTownSpawn: 96
    underTownSpawn: 255