Locale: en 
CompatibilityMode: false
SinkRateTicks: 20
SinkCheckTicks: 100
TracerRateTicks: 5
PilotTool: STICK
WorldGuardBlockMoveOnBuildPerm: true
WorldGuardBlockSinkOnPVPPerm: true
ManOverBoardTimeout: 30
FireballLifespan: 6
FireballPenetration: true
ProtectPilotedCrafts: true
DisableSpillProtection: false
RequireCreatePerm: false # require users to have the movecract.<CraftTypeName>.create permission in order to place command signs
RequireSneakingForDirectControl: false #Require if player should sneak in order to activate direct control
RequireNamePerm: false
TNTContactExplosives: true
DisableCrates: true
FadeWrecksAfter: 600
FadeTickCooldown: 20 #Number of ticks between each fading cycle
FadePercentageOfWreckPerCycle: 10.0 #Percentage of wreck to be faded in each fading cycle
ExtraFadeTimePerBlock: #List of blocks that will take longer time to fade
  CHEST: 600
  TRAPPED_CHEST: 600
  DISPENSER: 600
  DROPPER: 600
  FURNACE: 600
BlockQueueChunkSize: 200000
RepairTicksPerBlock: 10
RepairMoneyPerBlock: 10
RepairMaxPercent: 60.0
AllowCrewSigns: true
SetHomeToCrewSign: false
CraftsUseNetherPortals: false
CheckForUpdates: true
AssaultEnable: true # system to damage a region, incurring money damages. If enough damage is inflicted, ownership is lost. Ownership can be restored, and the region repaired, by paying damages
AssaultDamagesCapPercent: 1.0 # percentage of the total wealth of all members of the region which is the maximum damages that can be inflicted
AssaultCooldownHours: 24 # time before a region owner can have one of their regions assaulted again
AssaultDelay: 120 # time (in seconds) between when an assault is announced, and when it happens
AssaultDuration: 1800 # time (in seconds) for the assault
AssaultCostPercent: 0.25 # percentage of the total wealth of all members of the region which is the cost to assault it
AssaultDamagesPerBlock: 15 # the damages incurred for every block that would have been destroyed in an assault
AssaultMaxBalance: 5000000 # Maximum balance of each player that will be contributed to the cost & damages (previously hard coded at 5 million)
AssaultRequiredDefendersOnline: 2 # At least this many members or owners must be online for the region to be assaulted
AssaultRequiredOwnersOnline: 1 # At least this many owners must be online for the region to be assaulted, set to 0 to ignore
AssaultOwnerWeightPercent: 100 # Percentage of each Owner's balance (under the maximum) to include in the total cost & damages (Can be greater than 100)
AssaultMemberWeightPercent: 100 # Percentage of each Member's balance (under the maximum) to include in the total cost & damages (Can be greater than 100)
AssaultDestroyableBlocks: # these blocks will be removed if destroyed in assault. Other blocks will not be removed, but still count for damages. Don't include craft flyblocks, or blocks with metadata, or you can have issues.
  - STONE
  - GRASS
  - DIRT
  - COBBLESTONE
  - SAND
  - GRAVEL
  - IRON_ORE
  - COAL_ORE
  - LEAVES
  - SPONGE
  - SANDSTONE
  - LONG_GRASS
  - YELLOW_FLOWER
  - RED_ROSE
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - TNT
  - MOSSY_COBBLESTONE
  - SOIL
  - COBBLESTONE_STAIRS
  - REDSTONE_ORE
  - GLOWING_REDSTONE_ORE
  - SNOW
  - ICE
  - SNOW_BLOCK
  - CACTUS
  - CLAY
  - BRICK_STAIRS
  - SANDSTONE_STAIRS
  - EMERALD_ORE
  - LEAVES_2
  - LOG_2
  - ACACIA_STAIRS
  - PRISMARINE
  - SEA_LANTERN
  - PACKED_ICE
  - DOUBLE_PLANT
  - RED_SANDSTONE
  - RED_SANDSTONE_STAIRS
  - DOUBLE_STONE_SLAB2
  - STONE_SLAB2
  - FROSTED_ICE
SiegeEnable: true
DisableShadowBlocks: # These blocks will not cast shadows. This improves the speed of moving ships of these blocks immensely.
  - BED_BLOCK
  - WOOL
  - IRON_BLOCK
  - DOUBLE_STEP
  - STEP
  - REDSTONE_WIRE
  - SMOOTH_STAIRS
  - NETHER_BRICK
  - NETHER_BRICK_STAIRS
  - ENDER_STONE
  - TRAPPED_CHEST
  - REDSTONE_BLOCK
  - QUARTZ_BLOCK
  - QUARTZ_STAIRS
  - STAINED_CLAY
  - SLIME_BLOCK
  - COAL_BLOCK
  - END_BRICKS
WGCustomFlagsUsePilotFlag: false
WGCustomFlagsUseMoveFlag: false
WGCustomFlagsUseRotateFlag: false
WGCustomFlagsUseSinkFlag: false
DurabilityOverride:
  ENDER_STONE: 80
  END_BRICKS: 80
